volume: backups

projects:
  vault:
    containers: [vault_db, vault]
    passphrase: ${BORG_PASSPHRASE}

remotes:
  mega:
    type: mega
    user: ${MEGA_USER}
    pass: ${MEGA_PASSWORD}
    path: ${MEGA_PATH}
