FROM ubuntu:22.04

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

RUN apt-get update && apt-get install -y \
    curl \
    unzip \
    apt-transport-https \
    ca-certificates \
    gnupg \
    lsb-release \
    wget

ARG TARGETARCH
RUN if [ "$TARGETARCH" = "arm64" ]; then \
      wget https://borg.bauerj.eu/bin/borg-1.4.0-arm64 -O /usr/bin/borg; \
    else \
      wget https://github.com/borgbackup/borg/releases/download/1.4.0/borg-linux-glibc236 -O /usr/bin/borg; \
    fi && \
    chmod a+x /usr/bin/borg

RUN ln -s /usr/bin/borg /usr/local/bin/borgfs

RUN curl https://rclone.org/install.sh | bash && \
    which rclone && \
    rclone version

CMD ["/bin/bash"]