version: "3.7"
services:
  test-service:
    image: ubuntu
    command: tail -f /dev/null
    container_name: test-service
    ports:
      - 8080:80
    volumes:
      - test-volume1:/test-volume1
      - test-volume2:/test-volume2
  remote-backup:
    image: worker
    command: tail -f /dev/null
    container_name: remote-backup
    volumes:
      - remote-backup-data:/home/borg/backup
  worker:
    image: worker
    command: tail -f /dev/null
    container_name: worker
    volumes:
      - test-volume1:/input/test-volume1
      - test-volume2:/input/test-volume2
      - ./.ssh:/root/.ssh
volumes:
    test-volume1:
    test-volume2:
    docker-backup-db:
    remote-backup-data:
