version: "3.7"
services:
  test-service:
    image: ubuntu
    command: tail -f /dev/null
    container_name: test-service
    ports:
      - 8080:80
    volumes:
      - test-volume1:/test-volume1
      - test-volume2:/test-volume2
      - ./test-bind1:/test-bind1
      - ./test-bind2:/test-bind2
  db:
    image: postgres
    container_name: docker-backup-db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
        - 5432:5432
    volumes:
      - docker-backup-db:/var/lib/postgresql/data

volumes:
    test-volume1:
    test-volume2:
    docker-backup-db:
