// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import (
	interfaces "docker-backup/interfaces"

	mock "github.com/stretchr/testify/mock"
)

// BorgRepo is an autogenerated mock type for the BorgRepo type
type BorgRepo struct {
	mock.Mock
}

// CreateArchive provides a mock function with given fields: config
func (_m *BorgRepo) CreateArchive(config interfaces.CreateBorgArchiveConfig) error {
	ret := _m.Called(config)

	if len(ret) == 0 {
		panic("no return value specified for CreateArchive")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interfaces.CreateBorgArchiveConfig) error); ok {
		r0 = rf(config)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Info provides a mock function with given fields:
func (_m *BorgRepo) Info() (string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Info")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func() (string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListArchives provides a mock function with given fields:
func (_m *BorgRepo) ListArchives() (string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ListArchives")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func() (string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewBorgRepo creates a new instance of BorgRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBorgRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *BorgRepo {
	mock := &BorgRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
