// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import (
	interfaces "docker-backup/interfaces"

	mock "github.com/stretchr/testify/mock"
)

// BorgClient is an autogenerated mock type for the BorgClient type
type BorgClient struct {
	mock.Mock
}

// CreateRepo provides a mock function with given fields: config
func (_m *BorgClient) CreateRepo(config interfaces.CreateBorgRepoConfig) (interfaces.BorgRepo, error) {
	ret := _m.Called(config)

	if len(ret) == 0 {
		panic("no return value specified for CreateRepo")
	}

	var r0 interfaces.BorgRepo
	var r1 error
	if rf, ok := ret.Get(0).(func(interfaces.CreateBorgRepoConfig) (interfaces.BorgRepo, error)); ok {
		return rf(config)
	}
	if rf, ok := ret.Get(0).(func(interfaces.CreateBorgRepoConfig) interfaces.BorgRepo); ok {
		r0 = rf(config)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interfaces.BorgRepo)
		}
	}

	if rf, ok := ret.Get(1).(func(interfaces.CreateBorgRepoConfig) error); ok {
		r1 = rf(config)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRepo provides a mock function with given fields: config
func (_m *BorgClient) GetRepo(config interfaces.GetBorgRepoConfig) (interfaces.BorgRepo, error) {
	ret := _m.Called(config)

	if len(ret) == 0 {
		panic("no return value specified for GetRepo")
	}

	var r0 interfaces.BorgRepo
	var r1 error
	if rf, ok := ret.Get(0).(func(interfaces.GetBorgRepoConfig) (interfaces.BorgRepo, error)); ok {
		return rf(config)
	}
	if rf, ok := ret.Get(0).(func(interfaces.GetBorgRepoConfig) interfaces.BorgRepo); ok {
		r0 = rf(config)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interfaces.BorgRepo)
		}
	}

	if rf, ok := ret.Get(1).(func(interfaces.GetBorgRepoConfig) error); ok {
		r1 = rf(config)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewBorgClient creates a new instance of BorgClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBorgClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *BorgClient {
	mock := &BorgClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
