// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import (
	interfaces "docker-backup/interfaces"

	mock "github.com/stretchr/testify/mock"
)

// ContainerVolumesTable is an autogenerated mock type for the ContainerVolumesTable type
type ContainerVolumesTable struct {
	mock.Mock
}

// Add provides a mock function with given fields: c, v
func (_m *ContainerVolumesTable) Add(c interfaces.DatabaseContainer, v interfaces.DatabaseVolume) error {
	ret := _m.Called(c, v)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interfaces.DatabaseContainer, interfaces.DatabaseVolume) error); ok {
		r0 = rf(c, v)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields: c
func (_m *ContainerVolumesTable) GetAll(c interfaces.DatabaseContainer) ([]interfaces.DatabaseVolume, error) {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []interfaces.DatabaseVolume
	var r1 error
	if rf, ok := ret.Get(0).(func(interfaces.DatabaseContainer) ([]interfaces.DatabaseVolume, error)); ok {
		return rf(c)
	}
	if rf, ok := ret.Get(0).(func(interfaces.DatabaseContainer) []interfaces.DatabaseVolume); ok {
		r0 = rf(c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]interfaces.DatabaseVolume)
		}
	}

	if rf, ok := ret.Get(1).(func(interfaces.DatabaseContainer) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: c, volume_id
func (_m *ContainerVolumesTable) GetByID(c interfaces.DatabaseContainer, volume_id int64) (interfaces.DatabaseVolume, error) {
	ret := _m.Called(c, volume_id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 interfaces.DatabaseVolume
	var r1 error
	if rf, ok := ret.Get(0).(func(interfaces.DatabaseContainer, int64) (interfaces.DatabaseVolume, error)); ok {
		return rf(c, volume_id)
	}
	if rf, ok := ret.Get(0).(func(interfaces.DatabaseContainer, int64) interfaces.DatabaseVolume); ok {
		r0 = rf(c, volume_id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interfaces.DatabaseVolume)
		}
	}

	if rf, ok := ret.Get(1).(func(interfaces.DatabaseContainer, int64) error); ok {
		r1 = rf(c, volume_id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByName provides a mock function with given fields: c, volume_name
func (_m *ContainerVolumesTable) GetByName(c interfaces.DatabaseContainer, volume_name string) (interfaces.DatabaseVolume, error) {
	ret := _m.Called(c, volume_name)

	if len(ret) == 0 {
		panic("no return value specified for GetByName")
	}

	var r0 interfaces.DatabaseVolume
	var r1 error
	if rf, ok := ret.Get(0).(func(interfaces.DatabaseContainer, string) (interfaces.DatabaseVolume, error)); ok {
		return rf(c, volume_name)
	}
	if rf, ok := ret.Get(0).(func(interfaces.DatabaseContainer, string) interfaces.DatabaseVolume); ok {
		r0 = rf(c, volume_name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interfaces.DatabaseVolume)
		}
	}

	if rf, ok := ret.Get(1).(func(interfaces.DatabaseContainer, string) error); ok {
		r1 = rf(c, volume_name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Init provides a mock function with given fields:
func (_m *ContainerVolumesTable) Init() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Init")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Remove provides a mock function with given fields: c, v
func (_m *ContainerVolumesTable) Remove(c interfaces.DatabaseContainer, v interfaces.DatabaseVolume) error {
	ret := _m.Called(c, v)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interfaces.DatabaseContainer, interfaces.DatabaseVolume) error); ok {
		r0 = rf(c, v)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewContainerVolumesTable creates a new instance of ContainerVolumesTable. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewContainerVolumesTable(t interface {
	mock.TestingT
	Cleanup(func())
}) *ContainerVolumesTable {
	mock := &ContainerVolumesTable{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
