// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import (
	interfaces "docker-backup/interfaces"

	mock "github.com/stretchr/testify/mock"
)

// ContainersTable is an autogenerated mock type for the ContainersTable type
type ContainersTable struct {
	mock.Mock
}

// Add provides a mock function with given fields: c
func (_m *ContainersTable) Add(c interfaces.DatabaseContainer) (interfaces.DatabaseContainer, error) {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 interfaces.DatabaseContainer
	var r1 error
	if rf, ok := ret.Get(0).(func(interfaces.DatabaseContainer) (interfaces.DatabaseContainer, error)); ok {
		return rf(c)
	}
	if rf, ok := ret.Get(0).(func(interfaces.DatabaseContainer) interfaces.DatabaseContainer); ok {
		r0 = rf(c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interfaces.DatabaseContainer)
		}
	}

	if rf, ok := ret.Get(1).(func(interfaces.DatabaseContainer) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAll provides a mock function with given fields:
func (_m *ContainersTable) GetAll() ([]interfaces.DatabaseContainer, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []interfaces.DatabaseContainer
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]interfaces.DatabaseContainer, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []interfaces.DatabaseContainer); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]interfaces.DatabaseContainer)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: container_id
func (_m *ContainersTable) GetByID(container_id string) (interfaces.DatabaseContainer, error) {
	ret := _m.Called(container_id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 interfaces.DatabaseContainer
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (interfaces.DatabaseContainer, error)); ok {
		return rf(container_id)
	}
	if rf, ok := ret.Get(0).(func(string) interfaces.DatabaseContainer); ok {
		r0 = rf(container_id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interfaces.DatabaseContainer)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(container_id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByName provides a mock function with given fields: container_name
func (_m *ContainersTable) GetByName(container_name string) (interfaces.DatabaseContainer, error) {
	ret := _m.Called(container_name)

	if len(ret) == 0 {
		panic("no return value specified for GetByName")
	}

	var r0 interfaces.DatabaseContainer
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (interfaces.DatabaseContainer, error)); ok {
		return rf(container_name)
	}
	if rf, ok := ret.Get(0).(func(string) interfaces.DatabaseContainer); ok {
		r0 = rf(container_name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interfaces.DatabaseContainer)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(container_name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Init provides a mock function with given fields:
func (_m *ContainersTable) Init() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Init")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Remove provides a mock function with given fields: c
func (_m *ContainersTable) Remove(c interfaces.DatabaseContainer) error {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interfaces.DatabaseContainer) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewContainersTable creates a new instance of ContainersTable. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewContainersTable(t interface {
	mock.TestingT
	Cleanup(func())
}) *ContainersTable {
	mock := &ContainersTable{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
