// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import (
	interfaces "docker-backup/interfaces"

	mock "github.com/stretchr/testify/mock"
)

// DatabaseContainer is an autogenerated mock type for the DatabaseContainer type
type DatabaseContainer struct {
	mock.Mock
}

// AddVolume provides a mock function with given fields: _a0
func (_m *DatabaseContainer) AddVolume(_a0 interfaces.DatabaseVolume) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for AddVolume")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interfaces.DatabaseVolume) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetID provides a mock function with given fields:
func (_m *DatabaseContainer) GetID() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetID")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetName provides a mock function with given fields:
func (_m *DatabaseContainer) GetName() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetName")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetVolumeByID provides a mock function with given fields: id
func (_m *DatabaseContainer) GetVolumeByID(id int64) (interfaces.DatabaseVolume, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetVolumeByID")
	}

	var r0 interfaces.DatabaseVolume
	var r1 error
	if rf, ok := ret.Get(0).(func(int64) (interfaces.DatabaseVolume, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int64) interfaces.DatabaseVolume); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interfaces.DatabaseVolume)
		}
	}

	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetVolumeByName provides a mock function with given fields: name
func (_m *DatabaseContainer) GetVolumeByName(name string) (interfaces.DatabaseVolume, error) {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for GetVolumeByName")
	}

	var r0 interfaces.DatabaseVolume
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (interfaces.DatabaseVolume, error)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) interfaces.DatabaseVolume); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interfaces.DatabaseVolume)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetVolumes provides a mock function with given fields:
func (_m *DatabaseContainer) GetVolumes() ([]interfaces.DatabaseVolume, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetVolumes")
	}

	var r0 []interfaces.DatabaseVolume
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]interfaces.DatabaseVolume, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []interfaces.DatabaseVolume); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]interfaces.DatabaseVolume)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemoveVolume provides a mock function with given fields: _a0
func (_m *DatabaseContainer) RemoveVolume(_a0 interfaces.DatabaseVolume) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for RemoveVolume")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interfaces.DatabaseVolume) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewDatabaseContainer creates a new instance of DatabaseContainer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDatabaseContainer(t interface {
	mock.TestingT
	Cleanup(func())
}) *DatabaseContainer {
	mock := &DatabaseContainer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
