// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// DatabaseVolume is an autogenerated mock type for the DatabaseVolume type
type DatabaseVolume struct {
	mock.Mock
}

// GetID provides a mock function with given fields:
func (_m *DatabaseVolume) GetID() int64 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetID")
	}

	var r0 int64
	if rf, ok := ret.Get(0).(func() int64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int64)
	}

	return r0
}

// GetName provides a mock function with given fields:
func (_m *DatabaseVolume) GetName() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetName")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// NewDatabaseVolume creates a new instance of DatabaseVolume. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDatabaseVolume(t interface {
	mock.TestingT
	Cleanup(func())
}) *DatabaseVolume {
	mock := &DatabaseVolume{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
