// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import (
	interfaces "docker-backup/interfaces"

	mock "github.com/stretchr/testify/mock"
)

// DatabaseProject is an autogenerated mock type for the DatabaseProject type
type DatabaseProject struct {
	mock.Mock
}

// AddContainer provides a mock function with given fields: _a0
func (_m *DatabaseProject) AddContainer(_a0 interfaces.DatabaseContainer) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for AddContainer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interfaces.DatabaseContainer) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetContainerByID provides a mock function with given fields: id
func (_m *DatabaseProject) GetContainerByID(id string) (interfaces.DatabaseContainer, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetContainerByID")
	}

	var r0 interfaces.DatabaseContainer
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (interfaces.DatabaseContainer, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) interfaces.DatabaseContainer); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interfaces.DatabaseContainer)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetContainerByName provides a mock function with given fields: name
func (_m *DatabaseProject) GetContainerByName(name string) (interfaces.DatabaseContainer, error) {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for GetContainerByName")
	}

	var r0 interfaces.DatabaseContainer
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (interfaces.DatabaseContainer, error)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) interfaces.DatabaseContainer); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interfaces.DatabaseContainer)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetContainers provides a mock function with given fields:
func (_m *DatabaseProject) GetContainers() ([]interfaces.DatabaseContainer, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetContainers")
	}

	var r0 []interfaces.DatabaseContainer
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]interfaces.DatabaseContainer, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []interfaces.DatabaseContainer); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]interfaces.DatabaseContainer)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetID provides a mock function with given fields:
func (_m *DatabaseProject) GetID() int64 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetID")
	}

	var r0 int64
	if rf, ok := ret.Get(0).(func() int64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int64)
	}

	return r0
}

// GetName provides a mock function with given fields:
func (_m *DatabaseProject) GetName() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetName")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// RemoveContainer provides a mock function with given fields: _a0
func (_m *DatabaseProject) RemoveContainer(_a0 interfaces.DatabaseContainer) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for RemoveContainer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interfaces.DatabaseContainer) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewDatabaseProject creates a new instance of DatabaseProject. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDatabaseProject(t interface {
	mock.TestingT
	Cleanup(func())
}) *DatabaseProject {
	mock := &DatabaseProject{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
