// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import (
	interfaces "docker-backup/interfaces"

	mock "github.com/stretchr/testify/mock"
)

// DockerClient is an autogenerated mock type for the DockerClient type
type DockerClient struct {
	mock.Mock
}

// CreateContainer provides a mock function with given fields: image, volumes, binds
func (_m *DockerClient) CreateContainer(image string, volumes []interfaces.DockerVolume, binds []interfaces.DockerBind) (interfaces.DockerContainer, error) {
	ret := _m.Called(image, volumes, binds)

	if len(ret) == 0 {
		panic("no return value specified for CreateContainer")
	}

	var r0 interfaces.DockerContainer
	var r1 error
	if rf, ok := ret.Get(0).(func(string, []interfaces.DockerVolume, []interfaces.DockerBind) (interfaces.DockerContainer, error)); ok {
		return rf(image, volumes, binds)
	}
	if rf, ok := ret.Get(0).(func(string, []interfaces.DockerVolume, []interfaces.DockerBind) interfaces.DockerContainer); ok {
		r0 = rf(image, volumes, binds)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interfaces.DockerContainer)
		}
	}

	if rf, ok := ret.Get(1).(func(string, []interfaces.DockerVolume, []interfaces.DockerBind) error); ok {
		r1 = rf(image, volumes, binds)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateVolume provides a mock function with given fields: name
func (_m *DockerClient) CreateVolume(name string) (interfaces.DockerVolume, error) {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for CreateVolume")
	}

	var r0 interfaces.DockerVolume
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (interfaces.DockerVolume, error)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) interfaces.DockerVolume); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interfaces.DockerVolume)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetContainer provides a mock function with given fields: id
func (_m *DockerClient) GetContainer(id string) (interfaces.DockerContainer, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetContainer")
	}

	var r0 interfaces.DockerContainer
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (interfaces.DockerContainer, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) interfaces.DockerContainer); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interfaces.DockerContainer)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetVolume provides a mock function with given fields: name
func (_m *DockerClient) GetVolume(name string) (interfaces.DockerVolume, error) {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for GetVolume")
	}

	var r0 interfaces.DockerVolume
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (interfaces.DockerVolume, error)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) interfaces.DockerVolume); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interfaces.DockerVolume)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewDockerClient creates a new instance of DockerClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDockerClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *DockerClient {
	mock := &DockerClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
