// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import (
	interfaces "docker-backup/interfaces"

	mock "github.com/stretchr/testify/mock"
)

// DockerContainer is an autogenerated mock type for the DockerContainer type
type DockerContainer struct {
	mock.Mock
}

// Exec provides a mock function with given fields: cmd
func (_m *DockerContainer) Exec(cmd string) (string, error) {
	ret := _m.Called(cmd)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(cmd)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(cmd)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(cmd)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBinds provides a mock function with given fields:
func (_m *DockerContainer) GetBinds() []interfaces.DockerBind {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetBinds")
	}

	var r0 []interfaces.DockerBind
	if rf, ok := ret.Get(0).(func() []interfaces.DockerBind); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]interfaces.DockerBind)
		}
	}

	return r0
}

// GetEnv provides a mock function with given fields: key
func (_m *DockerContainer) GetEnv(key string) string {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for GetEnv")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(key)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetEnvs provides a mock function with given fields:
func (_m *DockerContainer) GetEnvs() map[string]string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetEnvs")
	}

	var r0 map[string]string
	if rf, ok := ret.Get(0).(func() map[string]string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}

	return r0
}

// GetID provides a mock function with given fields:
func (_m *DockerContainer) GetID() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetID")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetName provides a mock function with given fields:
func (_m *DockerContainer) GetName() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetName")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetVolumes provides a mock function with given fields:
func (_m *DockerContainer) GetVolumes() []interfaces.DockerVolume {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetVolumes")
	}

	var r0 []interfaces.DockerVolume
	if rf, ok := ret.Get(0).(func() []interfaces.DockerVolume); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]interfaces.DockerVolume)
		}
	}

	return r0
}

// Remove provides a mock function with given fields:
func (_m *DockerContainer) Remove() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RemoveEnv provides a mock function with given fields: key
func (_m *DockerContainer) RemoveEnv(key string) {
	_m.Called(key)
}

// SetEnv provides a mock function with given fields: key, value
func (_m *DockerContainer) SetEnv(key string, value string) {
	_m.Called(key, value)
}

// Start provides a mock function with given fields:
func (_m *DockerContainer) Start() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Stop provides a mock function with given fields:
func (_m *DockerContainer) Stop() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Stop")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StopAndRemove provides a mock function with given fields:
func (_m *DockerContainer) StopAndRemove() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for StopAndRemove")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewDockerContainer creates a new instance of DockerContainer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDockerContainer(t interface {
	mock.TestingT
	Cleanup(func())
}) *DockerContainer {
	mock := &DockerContainer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
