// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import (
	interfaces "docker-backup/interfaces"

	mock "github.com/stretchr/testify/mock"
)

// LocalBackup is an autogenerated mock type for the LocalBackup type
type LocalBackup struct {
	mock.Mock
}

// GetVolume provides a mock function with given fields:
func (_m *LocalBackup) GetVolume() interfaces.DockerVolume {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetVolume")
	}

	var r0 interfaces.DockerVolume
	if rf, ok := ret.Get(0).(func() interfaces.DockerVolume); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interfaces.DockerVolume)
		}
	}

	return r0
}

// GetVolumeName provides a mock function with given fields:
func (_m *LocalBackup) GetVolumeName() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetVolumeName")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// SetVolume provides a mock function with given fields: volume
func (_m *LocalBackup) SetVolume(volume interfaces.DockerVolume) {
	_m.Called(volume)
}

// SetVolumeName provides a mock function with given fields: name
func (_m *LocalBackup) SetVolumeName(name string) {
	_m.Called(name)
}

// NewLocalBackup creates a new instance of LocalBackup. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLocalBackup(t interface {
	mock.TestingT
	Cleanup(func())
}) *LocalBackup {
	mock := &LocalBackup{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
