// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import (
	interfaces "docker-backup/interfaces"

	mock "github.com/stretchr/testify/mock"
)

// ProjectsTable is an autogenerated mock type for the ProjectsTable type
type ProjectsTable struct {
	mock.Mock
}

// Add provides a mock function with given fields: p
func (_m *ProjectsTable) Add(p interfaces.DatabaseProject) (interfaces.DatabaseProject, error) {
	ret := _m.Called(p)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 interfaces.DatabaseProject
	var r1 error
	if rf, ok := ret.Get(0).(func(interfaces.DatabaseProject) (interfaces.DatabaseProject, error)); ok {
		return rf(p)
	}
	if rf, ok := ret.Get(0).(func(interfaces.DatabaseProject) interfaces.DatabaseProject); ok {
		r0 = rf(p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interfaces.DatabaseProject)
		}
	}

	if rf, ok := ret.Get(1).(func(interfaces.DatabaseProject) error); ok {
		r1 = rf(p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAll provides a mock function with given fields:
func (_m *ProjectsTable) GetAll() ([]interfaces.DatabaseProject, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []interfaces.DatabaseProject
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]interfaces.DatabaseProject, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []interfaces.DatabaseProject); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]interfaces.DatabaseProject)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: project_id
func (_m *ProjectsTable) GetByID(project_id int64) (interfaces.DatabaseProject, error) {
	ret := _m.Called(project_id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 interfaces.DatabaseProject
	var r1 error
	if rf, ok := ret.Get(0).(func(int64) (interfaces.DatabaseProject, error)); ok {
		return rf(project_id)
	}
	if rf, ok := ret.Get(0).(func(int64) interfaces.DatabaseProject); ok {
		r0 = rf(project_id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interfaces.DatabaseProject)
		}
	}

	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(project_id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByName provides a mock function with given fields: project_name
func (_m *ProjectsTable) GetByName(project_name string) (interfaces.DatabaseProject, error) {
	ret := _m.Called(project_name)

	if len(ret) == 0 {
		panic("no return value specified for GetByName")
	}

	var r0 interfaces.DatabaseProject
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (interfaces.DatabaseProject, error)); ok {
		return rf(project_name)
	}
	if rf, ok := ret.Get(0).(func(string) interfaces.DatabaseProject); ok {
		r0 = rf(project_name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interfaces.DatabaseProject)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(project_name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Init provides a mock function with given fields:
func (_m *ProjectsTable) Init() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Init")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Remove provides a mock function with given fields: p
func (_m *ProjectsTable) Remove(p interfaces.DatabaseProject) error {
	ret := _m.Called(p)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interfaces.DatabaseProject) error); ok {
		r0 = rf(p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewProjectsTable creates a new instance of ProjectsTable. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProjectsTable(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProjectsTable {
	mock := &ProjectsTable{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
