// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import (
	interfaces "docker-backup/interfaces"

	mock "github.com/stretchr/testify/mock"
)

// ProjectContainersTable is an autogenerated mock type for the ProjectContainersTable type
type ProjectContainersTable struct {
	mock.Mock
}

// Add provides a mock function with given fields: p, c
func (_m *ProjectContainersTable) Add(p interfaces.DatabaseProject, c interfaces.DatabaseContainer) error {
	ret := _m.Called(p, c)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interfaces.DatabaseProject, interfaces.DatabaseContainer) error); ok {
		r0 = rf(p, c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields: p
func (_m *ProjectContainersTable) GetAll(p interfaces.DatabaseProject) ([]interfaces.DatabaseContainer, error) {
	ret := _m.Called(p)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []interfaces.DatabaseContainer
	var r1 error
	if rf, ok := ret.Get(0).(func(interfaces.DatabaseProject) ([]interfaces.DatabaseContainer, error)); ok {
		return rf(p)
	}
	if rf, ok := ret.Get(0).(func(interfaces.DatabaseProject) []interfaces.DatabaseContainer); ok {
		r0 = rf(p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]interfaces.DatabaseContainer)
		}
	}

	if rf, ok := ret.Get(1).(func(interfaces.DatabaseProject) error); ok {
		r1 = rf(p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: p, container_id
func (_m *ProjectContainersTable) GetByID(p interfaces.DatabaseProject, container_id string) (interfaces.DatabaseContainer, error) {
	ret := _m.Called(p, container_id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 interfaces.DatabaseContainer
	var r1 error
	if rf, ok := ret.Get(0).(func(interfaces.DatabaseProject, string) (interfaces.DatabaseContainer, error)); ok {
		return rf(p, container_id)
	}
	if rf, ok := ret.Get(0).(func(interfaces.DatabaseProject, string) interfaces.DatabaseContainer); ok {
		r0 = rf(p, container_id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interfaces.DatabaseContainer)
		}
	}

	if rf, ok := ret.Get(1).(func(interfaces.DatabaseProject, string) error); ok {
		r1 = rf(p, container_id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByName provides a mock function with given fields: p, container_name
func (_m *ProjectContainersTable) GetByName(p interfaces.DatabaseProject, container_name string) (interfaces.DatabaseContainer, error) {
	ret := _m.Called(p, container_name)

	if len(ret) == 0 {
		panic("no return value specified for GetByName")
	}

	var r0 interfaces.DatabaseContainer
	var r1 error
	if rf, ok := ret.Get(0).(func(interfaces.DatabaseProject, string) (interfaces.DatabaseContainer, error)); ok {
		return rf(p, container_name)
	}
	if rf, ok := ret.Get(0).(func(interfaces.DatabaseProject, string) interfaces.DatabaseContainer); ok {
		r0 = rf(p, container_name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interfaces.DatabaseContainer)
		}
	}

	if rf, ok := ret.Get(1).(func(interfaces.DatabaseProject, string) error); ok {
		r1 = rf(p, container_name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Init provides a mock function with given fields:
func (_m *ProjectContainersTable) Init() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Init")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Remove provides a mock function with given fields: p, c
func (_m *ProjectContainersTable) Remove(p interfaces.DatabaseProject, c interfaces.DatabaseContainer) error {
	ret := _m.Called(p, c)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interfaces.DatabaseProject, interfaces.DatabaseContainer) error); ok {
		r0 = rf(p, c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewProjectContainersTable creates a new instance of ProjectContainersTable. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProjectContainersTable(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProjectContainersTable {
	mock := &ProjectContainersTable{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
