// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// SSHClient is an autogenerated mock type for the SSHClient type
type SSHClient struct {
	mock.Mock
}

// AddKeyfile provides a mock function with given fields: path
func (_m *SSHClient) AddKeyfile(path string) error {
	ret := _m.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for AddKeyfile")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(path)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AddKnownHost provides a mock function with given fields: host
func (_m *SSHClient) AddKnownHost(host string) error {
	ret := _m.Called(host)

	if len(ret) == 0 {
		panic("no return value specified for AddKnownHost")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(host)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewSSHClient creates a new instance of SSHClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSSHClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *SSHClient {
	mock := &SSHClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
