// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import (
	interfaces "docker-backup/interfaces"

	mock "github.com/stretchr/testify/mock"
)

// VolumesTable is an autogenerated mock type for the VolumesTable type
type VolumesTable struct {
	mock.Mock
}

// Add provides a mock function with given fields: v
func (_m *VolumesTable) Add(v interfaces.DatabaseVolume) (interfaces.DatabaseVolume, error) {
	ret := _m.Called(v)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 interfaces.DatabaseVolume
	var r1 error
	if rf, ok := ret.Get(0).(func(interfaces.DatabaseVolume) (interfaces.DatabaseVolume, error)); ok {
		return rf(v)
	}
	if rf, ok := ret.Get(0).(func(interfaces.DatabaseVolume) interfaces.DatabaseVolume); ok {
		r0 = rf(v)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interfaces.DatabaseVolume)
		}
	}

	if rf, ok := ret.Get(1).(func(interfaces.DatabaseVolume) error); ok {
		r1 = rf(v)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAll provides a mock function with given fields:
func (_m *VolumesTable) GetAll() ([]interfaces.DatabaseVolume, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []interfaces.DatabaseVolume
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]interfaces.DatabaseVolume, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []interfaces.DatabaseVolume); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]interfaces.DatabaseVolume)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: volume_id
func (_m *VolumesTable) GetByID(volume_id int64) (interfaces.DatabaseVolume, error) {
	ret := _m.Called(volume_id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 interfaces.DatabaseVolume
	var r1 error
	if rf, ok := ret.Get(0).(func(int64) (interfaces.DatabaseVolume, error)); ok {
		return rf(volume_id)
	}
	if rf, ok := ret.Get(0).(func(int64) interfaces.DatabaseVolume); ok {
		r0 = rf(volume_id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interfaces.DatabaseVolume)
		}
	}

	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(volume_id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByName provides a mock function with given fields: volume_name
func (_m *VolumesTable) GetByName(volume_name string) (interfaces.DatabaseVolume, error) {
	ret := _m.Called(volume_name)

	if len(ret) == 0 {
		panic("no return value specified for GetByName")
	}

	var r0 interfaces.DatabaseVolume
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (interfaces.DatabaseVolume, error)); ok {
		return rf(volume_name)
	}
	if rf, ok := ret.Get(0).(func(string) interfaces.DatabaseVolume); ok {
		r0 = rf(volume_name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interfaces.DatabaseVolume)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(volume_name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Init provides a mock function with given fields:
func (_m *VolumesTable) Init() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Init")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Remove provides a mock function with given fields: v
func (_m *VolumesTable) Remove(v interfaces.DatabaseVolume) error {
	ret := _m.Called(v)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interfaces.DatabaseVolume) error); ok {
		r0 = rf(v)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewVolumesTable creates a new instance of VolumesTable. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewVolumesTable(t interface {
	mock.TestingT
	Cleanup(func())
}) *VolumesTable {
	mock := &VolumesTable{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
